app/models/question.py
from app import db


# モデルに関する設定
class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(1000))
    body = db.Column(db.String(255))
    # Userに所有されている状態
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE', name='user_id__question_id_fk'))

    @classmethod
    def from_args(cls, title: str, body: str, user_id: int):
        instance = cls()
        instance.title = title
        instance.body = body
        instance.user_id = user_id
        return instance

app/models/user.py
from flask_login import UserMixin
# 追加
from sqlalchemy.orm import relationship
from werkzeug.security import generate_password_hash, check_password_hash

from app import db


# モデルに関する設定
class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(1000))
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))

    # 追加
    # user.questions と記述することでhas_manyなquestionを取得することができます
    questions = relationship('Question')

    # モデルからインスタンスを生成するときに使います。(利便性を高めるため)
    # passwordの暗号化も自動で行うことができるので、安全性も高めることができます。
    @classmethod
    def from_args(cls, name: str, email: str, password: str):
        instance = cls()
        instance.name = name
        instance.email = email
        instance.email = email
        if password is not None:
            # passwordがあれば暗号化します。
            instance.hash_password(password)
        return instance

    # 暗号化するためのメソッド。
    def hash_password(self, clean_password):
        self.password = generate_password_hash(str(clean_password), method='sha256')

    # 登録したpasswordとユーザーがログインフォームで入力したパスワードが正しいかどうかのチェックを行うメソッド
    def check_password(self, clean_password):
        return check_password_hash(self.password, clean_password)

app/__init__.py
# モジュールインポート
from flask import Flask, render_template
# データベースを利用するために追加
from flask_sqlalchemy import SQLAlchemy
# flaks-loginのライブラリ追加
from flask_login import LoginManager, login_required

# Flaskアプリの生成
app = Flask(__name__)

# ここから /// データベースの設定
app.secret_key = "super secret key"
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///qa-site.sqlite3'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
# ここまで /// データベースの設定

# sqlalchemyを通してflaskからdbアクセスをするための入り口
db = SQLAlchemy(app)

# flask-loginに関する設定
login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.init_app(app)

# データベースのimport
from app.models.user import User
from app.models.question import Question


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


# authに関するルーティングを追加
from app.views.auth import auth
from app.views.questions import questions

# authに関するルートをflaskアプリであるappに追加
app.register_blueprint(auth)
# url_prefixに「/questions」を入れると
# http://localhost:5000/questions/ というリンクになりわかりやすくなるので設定を追加しました
app.register_blueprint(questions, url_prefix='/questions')


# indexのルート設定
@app.route('/')
@login_required  # ここを追加
def index():
    return render_template('index.html')

app/views/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required

from app.services import auth_service

auth = Blueprint('auth', __name__)


# signupページと、postするページを共通化。
@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'GET':
        return render_template('auth/signup.html')
    else:
        user = auth_service.signup(request.form)
        if user:
            flash('メールアドレスは既に登録されています。')
            return redirect(url_for('index'))
        flash('新規登録に成功しました。')
        return redirect(url_for('index'))


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('auth/login.html')
    else:
        user = auth_service.login(request.form)
        if not user:
            flash('メールアドレスもしくはパスワードに誤りがあります。')
            return render_template('auth.login')
        flash('ログインしました。')
        return redirect(url_for('index'))


@auth.route('/logout')
@login_required
def logout():
    auth_service.logout()
    flash('ログアウトしました。')
    return redirect(url_for('auth.login'))

app/views/questions.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user

from app.services import question_service

questions = Blueprint('questions', __name__)


@questions.route('/')
@login_required  # ログインしていないと表示できないようにする
def find_all():
    questions = question_service.find_all()
    return render_template('questions/index.html', quesions=questions)


@questions.route('/<question_id>')
@login_required  # ログインしていないと表示できないようにする
def find_one(question_id: int):
    question = question_service.find_one(question_id)
    return render_template('questions/show.html', quesion=question)


@questions.route('/add', methods=['GET', 'POST'])
@login_required  # ログインしていないと表示できないようにする
def add():
    try:
        if request.method == 'GET':
            return render_template('questions/post.html')
        else:
            # postとputを一つのメソッドでできるようにquestion_idを入れてあるが、
            # 新規作成時はNoneにしておく。二つ目のrequet.formはformから送られてくる情報をそのままserviceに渡す
            # current_userはflask_loginの機能で、現在ログインしているユーザーの情報を取得することができる。
            question = question_service.save(None, current_user.id, request.form)
            if question is None:
                flash('Questionを追加することができませんでした。')
                return redirect(url_for('questions.add'))
            flash('Questionを追加しました。')
            return redirect(url_for('questions.find_all'))
    except Exception:
        flash('Questionを追加することができませんでした。')
        return redirect(url_for('questions.add'))


@questions.route('/update/<question_id>', methods=['GET', 'POST'])
@login_required  # ログインしていないと表示できないようにする
def update(question_id: int):
    try:
        if request.method == 'GET':
            question = question_service.find_one(question_id)
            return render_template('questions/update.html', question=question)
        else:
            question = question_service.save(question_id, current_user.id, request.form)
            if question is None:
                flash('Questionを修正することができませんでした。')
                return redirect(url_for('questions.update', question_id=question_id))
            flash('Questionを修正しました。')
            return redirect(url_for('questions.find_all'))
    except Exception:
        flash('Questionを修正することができませんでした。')
        return redirect(url_for('questions.update', question_id=question_id))


@questions.route('/delete/<question_id>', methods=['POST'])
@login_required  # ログインしていないと表示できないようにする
def delete(question_id: int):
    try:
        question_service.delete(question_id)
        flash('Questionを削除しました。')
        return redirect(url_for('questions.find_all'))
    except Exception:
        flash('Questionを削除することができませんでした。')
        return redirect(url_for('questions.find_all'))

app/templates/index.html
{% extends "layout.html" %}

{% block content %}
    <h1>
        Index page
    </h1>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>QA-Site</title>
</head>

<body>
<ul>
    {# ログインしていれば表示 #}
    {% if  current_user.is_authenticated %}
        <li><a href="{{ url_for('index') }}">Index</a></li>
        {#ここに追加#}
        <li><a href="{{ url_for('questions.find_all') }}">Questions</a></li>
        <li><a href="{{ url_for('auth.logout') }}">ログアウト</a></li>
    {% endif %}

    {#ログインしていなければ表示#}
    {% if not current_user.is_authenticated %}
        <li><a href="{{ url_for('auth.signup') }}">新規登録</a></li>
        <li><a href="{{ url_for('auth.login') }}">ログイン</a></li>
    {% endif %}
</ul>
{# flaskのメッセージを表示 #}
{% with messages = get_flashed_messages() %}
    {% if messages %}
        <div>
            {{ messages[0] }}
        </div>
    {% endif %}
{% endwith %}
{% block content %}
{% endblock %}


</body>

</html>

app/templates/questions/index.html
{% extends "layout.html" %}

{% block content %}
    <h1>Questions</h1>
    <ul>
        <li><a href="{{ url_for('questions.find_all') }}">Index</a></li>
        <li><a href="{{ url_for('questions.add') }}">追加</a></li>
    </ul>

    {% for question in quesions %}
        <p>{{ question.title }} // {{ question.body }}
            <span><button><a href="{{ url_for('questions.find_one', question_id=question.id) }}">detail</a></button></span>
            <span><button><a href="{{ url_for('questions.update', question_id=question.id) }}">update</a></button></span>
        <form action="{{ url_for('questions.delete', question_id=question.id) }}" method="POST">
            <button type="submit"><a>delete</a></button>
        </form>
        </p>
    {% endfor %}

{% endblock %}

app/templates/questions/post.html
{% extends "layout.html" %}

{% block content %}
    <div>
        <h3>Questionの追加</h3>
        <div>
            <form action="/questions/add" method="POST">
                <div>
                    <div>
                        <input type="text" name="title" placeholder="Title" autofocus="">
                    </div>
                </div>

                <div>
                    <div>
                        <input type="text" name="body" placeholder="Body" autofocus="">
                    </div>
                </div>
                <button>追加する</button>
            </form>
        </div>
    </div>
{% endblock %}l

app/templates/questions/show.html
{% extends "layout.html" %}

{% block content %}
    <h1>Questions</h1>
    <ul>
        <li><a href="{{ url_for('questions.find_all') }}">Index</a></li>
        <li><a href="{{ url_for('questions.add') }}">追加</a></li>
    </ul>
    <ul>
        <p>Title：{{ question.title }}</p>
        <p>Body：{{ question.body }}</p>
    </ul>
{% endblock %}

app/templates/questions/update.html
{% extends "layout.html" %}

{% block content %}
    <div>
        <h3>Questionの追加</h3>
        <div>
            <form action="/questions/update/{{ question.id }}" method="POST">
                <div>
                    <div>
                        <input type="text" name="title" placeholder="Title" value="{{ question.title }}">
                    </div>
                </div>

                <div>
                    <div>
                        <input type="text" name="body" placeholder="Body" value="{{ question.body }}">
                    </div>
                </div>
                <button>修正する</button>
            </form>
        </div>
    </div>
{% endblock %}l